import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { signIn, signOut, useSession } from 'next-auth/react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { data } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={() => signIn()}>로그인</button>
        <button onClick={() => signOut()}>로그아웃</button>
        <img src={data?.user?.image ?? ''} />
        <p>{data?.user?.email}</p>
        <form action="/api/product" method="post" encType="multipart/form-data">
          <input type="file" name="file" />
          <input name="name" />
          <input name="color" />
          <input type="submit" />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        하이
      </footer>
    </div>
  );
};

export default Home;
